// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlc

import (
	"context"
)

const getTableCounts = `-- name: GetTableCounts :one
SELECT
    (SELECT COUNT(*) FROM book)::bigint AS books_count,
    (SELECT COUNT(*) FROM machine)::bigint AS machines_count,
    (SELECT COUNT(*) FROM book_machine)::bigint AS book_machine_count
`

type GetTableCountsRow struct {
	BooksCount       int64
	MachinesCount    int64
	BookMachineCount int64
}

func (q *Queries) GetTableCounts(ctx context.Context) (GetTableCountsRow, error) {
	row := q.db.QueryRow(ctx, getTableCounts)
	var i GetTableCountsRow
	err := row.Scan(&i.BooksCount, &i.MachinesCount, &i.BookMachineCount)
	return i, err
}

const truncateCoreTables = `-- name: TruncateCoreTables :exec
TRUNCATE TABLE
    book_machine,
    book,
    machine
RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateCoreTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCoreTables)
	return err
}
