// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBookMetricsSummary = `-- name: GetBookMetricsSummary :many
SELECT
    b.id AS book_id,
    b.title,
    b.author,
    COUNT(bm.id)::bigint AS clicks,
    COUNT(DISTINCT bm.session_id)::bigint AS unique_sessions
FROM book_metrics bm
JOIN book b ON b.id = bm.book_id
WHERE bm.date >= $1
  AND bm.date < $2
  AND ($3::boolean IS NULL OR bm.qr = $3::boolean)
GROUP BY b.id, b.title, b.author
ORDER BY clicks DESC, b.title
`

type GetBookMetricsSummaryParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Qr        pgtype.Bool
}

type GetBookMetricsSummaryRow struct {
	BookID         int64
	Title          string
	Author         string
	Clicks         int64
	UniqueSessions int64
}

func (q *Queries) GetBookMetricsSummary(ctx context.Context, arg GetBookMetricsSummaryParams) ([]GetBookMetricsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getBookMetricsSummary, arg.StartDate, arg.EndDate, arg.Qr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookMetricsSummaryRow
	for rows.Next() {
		var i GetBookMetricsSummaryRow
		if err := rows.Scan(
			&i.BookID,
			&i.Title,
			&i.Author,
			&i.Clicks,
			&i.UniqueSessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMachineMetricsSummary = `-- name: GetMachineMetricsSummary :many
SELECT
    m.id AS machine_id,
    m.location,
    COUNT(DISTINCT mm.id)::bigint AS views,
    COUNT(DISTINCT bm.id)::bigint AS book_clicks,
    COUNT(DISTINCT COALESCE(NULLIF(mm.session_id, 'unknown'), NULLIF(bm.session_id, 'unknown')))::bigint AS unique_sessions
FROM machine m
LEFT JOIN machine_metrics mm ON mm.machine_id = m.id
    AND mm.date >= $1
    AND mm.date < $2
    AND ($3::boolean IS NULL OR mm.qr = $3::boolean)
LEFT JOIN book_metrics bm ON bm.machine_id = m.id
    AND bm.date >= $1
    AND bm.date < $2
    AND ($3::boolean IS NULL OR bm.qr = $3::boolean)
GROUP BY m.id, m.location
ORDER BY views DESC, book_clicks DESC, m.location
`

type GetMachineMetricsSummaryParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Qr        pgtype.Bool
}

type GetMachineMetricsSummaryRow struct {
	MachineID      int64
	Location       string
	Views          int64
	BookClicks     int64
	UniqueSessions int64
}

func (q *Queries) GetMachineMetricsSummary(ctx context.Context, arg GetMachineMetricsSummaryParams) ([]GetMachineMetricsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getMachineMetricsSummary, arg.StartDate, arg.EndDate, arg.Qr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMachineMetricsSummaryRow
	for rows.Next() {
		var i GetMachineMetricsSummaryRow
		if err := rows.Scan(
			&i.MachineID,
			&i.Location,
			&i.Views,
			&i.BookClicks,
			&i.UniqueSessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsTotals = `-- name: GetMetricsTotals :one
SELECT
    (SELECT COUNT(*) FROM book_metrics bm
     WHERE bm.date >= $1
       AND bm.date < $2
       AND ($3::boolean IS NULL OR bm.qr = $3::boolean))::bigint AS book_clicks,
    (SELECT COUNT(*) FROM machine_metrics mm
     WHERE mm.date >= $1
       AND mm.date < $2
       AND ($3::boolean IS NULL OR mm.qr = $3::boolean))::bigint AS machine_views,
    (SELECT COUNT(DISTINCT bm.session_id) FROM book_metrics bm
     WHERE bm.date >= $1
       AND bm.date < $2
       AND ($3::boolean IS NULL OR bm.qr = $3::boolean))::bigint AS unique_sessions
`

type GetMetricsTotalsParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
	Qr        pgtype.Bool
}

type GetMetricsTotalsRow struct {
	BookClicks     int64
	MachineViews   int64
	UniqueSessions int64
}

func (q *Queries) GetMetricsTotals(ctx context.Context, arg GetMetricsTotalsParams) (GetMetricsTotalsRow, error) {
	row := q.db.QueryRow(ctx, getMetricsTotals, arg.StartDate, arg.EndDate, arg.Qr)
	var i GetMetricsTotalsRow
	err := row.Scan(&i.BookClicks, &i.MachineViews, &i.UniqueSessions)
	return i, err
}

const getTableCounts = `-- name: GetTableCounts :one
SELECT
    (SELECT COUNT(*) FROM book)::bigint AS books_count,
    (SELECT COUNT(*) FROM machine)::bigint AS machines_count,
    (SELECT COUNT(*) FROM book_machine)::bigint AS book_machine_count
`

type GetTableCountsRow struct {
	BooksCount       int64
	MachinesCount    int64
	BookMachineCount int64
}

func (q *Queries) GetTableCounts(ctx context.Context) (GetTableCountsRow, error) {
	row := q.db.QueryRow(ctx, getTableCounts)
	var i GetTableCountsRow
	err := row.Scan(&i.BooksCount, &i.MachinesCount, &i.BookMachineCount)
	return i, err
}

const truncateCoreTables = `-- name: TruncateCoreTables :exec
TRUNCATE TABLE
    book_machine,
    book,
    machine
RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateCoreTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCoreTables)
	return err
}
