// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book_machine.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBookMachineByMachineID = `-- name: DeleteBookMachineByMachineID :exec
DELETE FROM book_machine
WHERE machine_id = $1
`

func (q *Queries) DeleteBookMachineByMachineID(ctx context.Context, machineID int64) error {
	_, err := q.db.Exec(ctx, deleteBookMachineByMachineID, machineID)
	return err
}

const getBookByRowAndCol = `-- name: GetBookByRowAndCol :one
SELECT b.id, b.title, b.author, b.summary, b.image, b.price
FROM book_machine bm
JOIN book b ON b.id = bm.book_id
WHERE bm.row = $1
  AND bm.col = $2
LIMIT 1
`

type GetBookByRowAndColParams struct {
	Row int32
	Col int32
}

func (q *Queries) GetBookByRowAndCol(ctx context.Context, arg GetBookByRowAndColParams) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByRowAndCol, arg.Row, arg.Col)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Image,
		&i.Price,
	)
	return i, err
}

const getMachineWithBooks = `-- name: GetMachineWithBooks :many
SELECT
    m.id AS machine_id,
    m.location,
    m.rows AS machine_rows,
    m.columns AS machine_columns,
    b.id AS book_id,
    b.title,
    b.author,
    b.summary,
    b.image,
    b.price,
    bm.row,
    bm.col
FROM machine m
LEFT JOIN book_machine bm ON bm.machine_id = m.id
LEFT JOIN book b ON b.id = bm.book_id
WHERE m.id = $1
ORDER BY bm.row, bm.col
`

type GetMachineWithBooksRow struct {
	MachineID      int64
	Location       string
	MachineRows    int32
	MachineColumns int32
	BookID         pgtype.Int8
	Title          pgtype.Text
	Author         pgtype.Text
	Summary        pgtype.Text
	Image          pgtype.Text
	Price          pgtype.Text
	Row            pgtype.Int4
	Col            pgtype.Int4
}

func (q *Queries) GetMachineWithBooks(ctx context.Context, id int64) ([]GetMachineWithBooksRow, error) {
	rows, err := q.db.Query(ctx, getMachineWithBooks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMachineWithBooksRow
	for rows.Next() {
		var i GetMachineWithBooksRow
		if err := rows.Scan(
			&i.MachineID,
			&i.Location,
			&i.MachineRows,
			&i.MachineColumns,
			&i.BookID,
			&i.Title,
			&i.Author,
			&i.Summary,
			&i.Image,
			&i.Price,
			&i.Row,
			&i.Col,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBookMachine = `-- name: InsertBookMachine :exec
INSERT INTO book_machine (
    machine_id,
    book_id,
    row,
    col
) VALUES ($1, $2, $3, $4)
`

type InsertBookMachineParams struct {
	MachineID int64
	BookID    int64
	Row       int32
	Col       int32
}

func (q *Queries) InsertBookMachine(ctx context.Context, arg InsertBookMachineParams) error {
	_, err := q.db.Exec(ctx, insertBookMachine,
		arg.MachineID,
		arg.BookID,
		arg.Row,
		arg.Col,
	)
	return err
}

const machineHasLoadedBooksOutsideBounds = `-- name: MachineHasLoadedBooksOutsideBounds :one
SELECT EXISTS (
    SELECT 1
    FROM book_machine
    WHERE machine_id = $1
      AND (row >= $2 OR col >= $3)
)
`

type MachineHasLoadedBooksOutsideBoundsParams struct {
	MachineID int64
	Rows      int32
	Cols      int32
}

func (q *Queries) MachineHasLoadedBooksOutsideBounds(ctx context.Context, arg MachineHasLoadedBooksOutsideBoundsParams) (bool, error) {
	row := q.db.QueryRow(ctx, machineHasLoadedBooksOutsideBounds, arg.MachineID, arg.Rows, arg.Cols)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateBookPosition = `-- name: UpdateBookPosition :exec
UPDATE book_machine
SET row = $2,
    col = $3
WHERE book_id = $1
`

type UpdateBookPositionParams struct {
	BookID int64
	Row    int32
	Col    int32
}

func (q *Queries) UpdateBookPosition(ctx context.Context, arg UpdateBookPositionParams) error {
	_, err := q.db.Exec(ctx, updateBookPosition, arg.BookID, arg.Row, arg.Col)
	return err
}
