// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book.sql

package sqlc

import (
	"context"
)

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM book
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, summary, image, price
FROM book
WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Image,
		&i.Price,
	)
	return i, err
}

const insertBook = `-- name: InsertBook :one
INSERT INTO book (
    title,
    author,
    summary,
    image,
    price
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id
`

type InsertBookParams struct {
	Title   string
	Author  string
	Summary string
	Image   string
	Price   string
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBook,
		arg.Title,
		arg.Author,
		arg.Summary,
		arg.Image,
		arg.Price,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, summary, image, price
FROM book
ORDER BY id
LIMIT 100
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Summary,
			&i.Image,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE book
SET title = $2,
    author = $3,
    summary = $4,
    price = $5
WHERE id = $1
`

type UpdateBookParams struct {
	ID      int64
	Title   string
	Author  string
	Summary string
	Price   string
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.Exec(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Summary,
		arg.Price,
	)
	return err
}

const updateBookImage = `-- name: UpdateBookImage :exec
UPDATE book
SET image = $2
WHERE id = $1
`

type UpdateBookImageParams struct {
	ID    int64
	Image string
}

func (q *Queries) UpdateBookImage(ctx context.Context, arg UpdateBookImageParams) error {
	_, err := q.db.Exec(ctx, updateBookImage, arg.ID, arg.Image)
	return err
}
