// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machine.sql

package sqlc

import (
	"context"
)

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machine
WHERE id = $1
`

func (q *Queries) DeleteMachine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMachine, id)
	return err
}

const getMachineById = `-- name: GetMachineById :one
SELECT id, location, rows, columns
FROM machine
WHERE id = $1
`

func (q *Queries) GetMachineById(ctx context.Context, id int64) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachineById, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Rows,
		&i.Columns,
	)
	return i, err
}

const insertMachine = `-- name: InsertMachine :one
INSERT INTO machine (
    location,
    rows,
    columns
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type InsertMachineParams struct {
	Location string
	Rows     int32
	Columns  int32
}

func (q *Queries) InsertMachine(ctx context.Context, arg InsertMachineParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMachine, arg.Location, arg.Rows, arg.Columns)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMachineMetric = `-- name: InsertMachineMetric :one
INSERT INTO machine_metrics (
    machine_id,
    date,
    qr,
    source,
    admin,
    session_id
) VALUES (
    $1, NOW()::date, $2, $3, $4, $5
)
RETURNING id
`

type InsertMachineMetricParams struct {
	MachineID int64
	Qr        bool
	Source    string
	Admin     bool
	SessionID string
}

func (q *Queries) InsertMachineMetric(ctx context.Context, arg InsertMachineMetricParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMachineMetric,
		arg.MachineID,
		arg.Qr,
		arg.Source,
		arg.Admin,
		arg.SessionID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, location, rows, columns
FROM machine
ORDER BY id
LIMIT 100
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Location,
			&i.Rows,
			&i.Columns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMachine = `-- name: UpdateMachine :exec
UPDATE machine
SET location = $2,
    rows = $3,
    columns = $4
WHERE id = $1
`

type UpdateMachineParams struct {
	ID       int64
	Location string
	Rows     int32
	Columns  int32
}

func (q *Queries) UpdateMachine(ctx context.Context, arg UpdateMachineParams) error {
	_, err := q.db.Exec(ctx, updateMachine,
		arg.ID,
		arg.Location,
		arg.Rows,
		arg.Columns,
	)
	return err
}

const updateMachineRowsCols = `-- name: UpdateMachineRowsCols :exec
UPDATE machine
SET rows = $1,
    columns = $2
WHERE id = $3
`

type UpdateMachineRowsColsParams struct {
	Rows int32
	Cols int32
	ID   int64
}

func (q *Queries) UpdateMachineRowsCols(ctx context.Context, arg UpdateMachineRowsColsParams) error {
	_, err := q.db.Exec(ctx, updateMachineRowsCols, arg.Rows, arg.Cols, arg.ID)
	return err
}
