// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Book struct {
	ID      int64
	Title   string
	Author  string
	Summary string
	Image   string
	Price   string
}

type BookMachine struct {
	MachineID int64
	BookID    int64
	Row       int32
	Col       int32
}

type Machine struct {
	ID       int64
	Location string
	Rows     int32
	Columns  int32
}
