// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID      int64
	Title   string
	Author  string
	Summary string
	Image   string
	Price   string
}

type BookMachine struct {
	MachineID int64
	BookID    int64
	Row       int32
	Col       int32
}

type BookMetric struct {
	ID        int64
	BookID    int64
	MachineID int64
	Date      pgtype.Date
	Qr        bool
	Source    pgtype.Text
	SessionID string
}

type Machine struct {
	ID       int64
	Location string
	Rows     int32
	Columns  int32
}

type MachineMetric struct {
	ID        int64
	MachineID int64
	Date      pgtype.Date
	Qr        bool
	Source    string
	Admin     bool
	SessionID string
}
