FROM mcr.microsoft.com/playwright:v1.51.1-noble

WORKDIR /work

COPY *.spec.js /work/
COPY fixtures /work/fixtures

RUN npm init -y && npm install --save-dev @playwright/test@1.51.1

CMD ["npx", "playwright", "test", "--reporter=line"]
