// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book_machine.sql

package sqlc

import (
	"context"
)

const deleteBookMachineByMachineID = `-- name: DeleteBookMachineByMachineID :exec
DELETE FROM book_machine
WHERE machine_id = $1
`

func (q *Queries) DeleteBookMachineByMachineID(ctx context.Context, machineID int64) error {
	_, err := q.db.Exec(ctx, deleteBookMachineByMachineID, machineID)
	return err
}

const getBookByRowAndCol = `-- name: GetBookByRowAndCol :one
SELECT b.id, b.title, b.author, b.summary, b.image, b.price
FROM book_machine bm
JOIN book b ON b.id = bm.book_id
WHERE bm.row = $1
  AND bm.col = $2
LIMIT 1
`

type GetBookByRowAndColParams struct {
	Row int32
	Col int32
}

func (q *Queries) GetBookByRowAndCol(ctx context.Context, arg GetBookByRowAndColParams) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByRowAndCol, arg.Row, arg.Col)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Summary,
		&i.Image,
		&i.Price,
	)
	return i, err
}

const insertBookMachine = `-- name: InsertBookMachine :exec
INSERT INTO book_machine (
    machine_id,
    book_id,
    row,
    col
) VALUES ($1, $2, $3, $4)
`

type InsertBookMachineParams struct {
	MachineID int64
	BookID    int64
	Row       int32
	Col       int32
}

func (q *Queries) InsertBookMachine(ctx context.Context, arg InsertBookMachineParams) error {
	_, err := q.db.Exec(ctx, insertBookMachine,
		arg.MachineID,
		arg.BookID,
		arg.Row,
		arg.Col,
	)
	return err
}

const updateBookPosition = `-- name: UpdateBookPosition :exec
UPDATE book_machine
SET row = $2,
    col = $3
WHERE book_id = $1
`

type UpdateBookPositionParams struct {
	BookID int64
	Row    int32
	Col    int32
}

func (q *Queries) UpdateBookPosition(ctx context.Context, arg UpdateBookPositionParams) error {
	_, err := q.db.Exec(ctx, updateBookPosition, arg.BookID, arg.Row, arg.Col)
	return err
}
