// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machine.sql

package sqlc

import (
	"context"
)

const insertMachine = `-- name: InsertMachine :one
INSERT INTO machine (
    location,
    rows,
    columns
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type InsertMachineParams struct {
	Location string
	Rows     int32
	Columns  int32
}

func (q *Queries) InsertMachine(ctx context.Context, arg InsertMachineParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMachine, arg.Location, arg.Rows, arg.Columns)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, location, rows, columns
FROM machine
ORDER BY id
LIMIT 100
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Location,
			&i.Rows,
			&i.Columns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
